### ISSUE TITLE
It Is Hard To Read In The Ui

### ISSUE THREAD

**Issue by WindowsAurora** [Skythrew/kattpad#8]
When i go read a story the ui looks scuffed and hard to read. 
Maybe change the text color to pure black?
Also this ui following the material you design/color scheme or dark mode would be nice in a future release.
![Screenshot_20240815_154003_Kattpad](https://github.com/user-attachments/assets/109b5ec7-c5b9-4916-98e4-e4943c460337)

**Comment by Skythrew** [comment]
Oh yes I forgot to force the text color to pure black and to not follow the Material Theme, I'm going to fix this for today's release.

**Comment by Skythrew** [comment]
> Also this ui following the material you design/color scheme or dark mode would be nice in a future release.

 It's actually a choice to have made the background white to improve readability as the default Material You color scheme 
isn't really good for the reading surface but I'll think about it :+1:
